#!/bin/sh
. "$(dirname "$0")/_/husky.sh"

## ------------------------------
#  TERRAFORM (validate & format)
## ------------------------------
terraform -chdir=libs/multi-cart-iac validate
terraform -chdir=libs/multi-cart-iac fmt

## ------------------------------
#  LINT
## ------------------------------
yarn affected:lint


## ------------------------------
#  TEST (wip)
## ------------------------------

# NOT READY YET: yarn affected:test


# export NODE_OPTIONS="--max-old-space-size=8192"


