#!/bin/sh
. "$(dirname "$0")/_/husky.sh"

## ------------------------------
#  TERRAFORM (validate & format)
## ------------------------------
terraform -chdir=libs/multi-cart-iac validate
terraform -chdir=libs/multi-cart-iac fmt

## ------------------------------
#  LINT
## ------------------------------
yarn affected:lint


## ------------------------------
#  TEST (wip)
## ------------------------------

# NOT READY YET: yarn affected:test
# test API only if changes made to iac stuff
if (git status | grep "libs/multi-cart-iac/") 
then
     yarn test-iac
else 
    exit
fi


# export NODE_OPTIONS="--max-old-space-size=8192"


