name: Create develop pull request from feature branch commit
on:
  push:
    branches:
      - 'kg-**' 
jobs:
  developPromotion:
    runs-on: ubuntu-latest
    steps:
      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v3
        with:
          branch: develop