name: Create develop pull request from feature branch commit
on:
  push:
    branches:
      - 'kg-**' 
jobs:
  developPromotion:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v3
        with:
          base: develop
          branch: kg-2021-05-12-iac-hello-tf-cloud