# thx: https://dev.to/rikurouvila/how-to-trigger-a-github-action-with-an-htt-request-545

name: Node.js CI

on:
  repository_dispatch:
    types: tf-test-dev-and-promote-to-prod

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Testing
        run: echo "Hello Repository Dispatch! 💚"
