# thx: https://dev.to/rikurouvila/how-to-trigger-a-github-action-with-an-htt-request-545

name: Node.js CI

on:
  repository_dispatch:
  schedule:
    - cron: '5 12 * * 0'

jobs:
  build:
    runs-on: ubuntu-latest
